name: Generate GitHub Metrics

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: "repositories"
          plugin_activity: "yes"
          plugin_languages: "yes"
          plugin_stars: "yes"
          plugin_achievements: "yes"
          plugin_people: "yes"
          plugin_notable: "yes"
          plugin_followup: "yes"
          config_timezone: "Europe/Bucharest"
