# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: GitHub Metrics

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:
  push:
    branches:
      - master
      - main

jobs:
  generate-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # GitHub username
          user: xl-spooky

          template: classic

          base: header, activity, community, repositories, metadata

          config_timezone: Europe/Rome

          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: B

          plugin_code: yes
          plugin_code_days: 7
          plugin_code_lines: 50
          plugin_code_load: 500
          plugin_code_visibility: public

          plugin_languages: yes
          plugin_languages_analysis_timeout: 20
          plugin_languages_analysis_timeout_repositories: 10
          plugin_languages_categories: markup, programming, data
          plugin_languages_colors: github
          plugin_languages_limit: 10
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 30
          plugin_languages_recent_load: 400
          plugin_languages_sections: most-used, recently-used
          plugin_languages_threshold: 0%

          plugin_notable: yes
          plugin_notable_filter: stars:>10
          plugin_notable_from: organization, user
          plugin_notable_indepth: yes
          plugin_notable_repositories: yes
          plugin_notable_types: commit, issue, pull_request, stars

          plugin_trophies: yes
          plugin_trophies_display: detailed

          plugin_commit_activity: yes
          plugin_commit_activity_days: 30

          plugin_pull_requests: yes
          plugin_pull_requests_days: 30
          plugin_pull_requests_status: all

          plugin_issues: yes
          plugin_issues_days: 30
          plugin_issues_status: all

          plugin_forks: yes

          plugin_stars: yes
          plugin_stars_days: 30

          plugin_releases: yes
          plugin_releases_days: 30

          plugin_continuous_integration: yes

          plugin_topics: yes
          plugin_topics_limit: 10

          plugin_license: yes
          plugin_license_color: yes
          plugin_license_repositories: yes

          config_custom_css: |
            /* Customize your metrics page */
            .metrics-header {
              background-color: #282c34;
              color: #61dafb;
            }
            .metrics-section {
              border-bottom: 1px solid #eaeaea;
            }
